
name: Java CI

on:
  release:
    branches:
     -main

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        
    - name: Compile and Test Java Testing QA
      run: |
        javac -d ./bin ./src/*.java
        java -cp ./bin OddNumberChecker
